apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
    tier: database
  name: mysql
  namespace: dalston
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      tier: database
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
        tier: database
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: mysql-persistence-volume
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_SERVICE_HOST
          value: "pages-mysql"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "pages"
        - name: MYSQL_USER
          value: "root"
      volumes:
        - name: mysql-persistence-volume
          emptyDir: {}
